### PR TITLE
Fix IMU update vector

### LINKED ISSUE #432: [EKF] Parameter  `imuN` contains and uses fields for x,y,z, vx,vy,vz
The fields for `x,y,z, vx,vy,vz` in the parameter `imuN` first of all make no sense, because an Imu message does not contain these; even worse though, they are actually used by the filter.
Hence, if somebody was to set the field of `vx` to `true` the filter will accept this and introduce a velocity measurement of value 0.0 with 0.0 covariance, which is highly undesired.

The parameters should either be removed or at least it should be ensured, that `true` entries of non-existing data does not have an impact.

### PR DESCRIPTION
**Pull request by johuber**
Closes #432.

Previously if the config entries for position or linear_speed update from IMU topic were set to true:
*  measurements with values 0.0 were introduced into state estimation

Since sensor_msgs/Imu does not contain any infos about these fields they should never be read. Now they are masked and ignored, additionally there is a `ROS_WARN` output if they are set true, to alert the user that this does not have any effect.

### CODE REVIEW

**Comment by ayrton04** [comment]
Thanks for fixing this! I'll take a look later today or tomorrow.

File: src/ros_filter.cpp [hunk 1]
```diff
@@ -1367,7 +1367,31 @@ namespace RobotLocalization
...
         std::vector<int> updateVec = loadUpdateConfig(imuTopicName);
 
+        // sanity checks for update config settings
+        std::vector<int> positionUpdateVec(updateVec.begin() + POSITION_OFFSET,
+                                           updateVec.begin() + POSITION_OFFSET + POSITION_SIZE);
+        int positionUpdateSum = std::accumulate(positionUpdateVec.begin(), positionUpdateVec.end(), 0);
+        if (positionUpdateSum > 0)
+        {
+          ROS_WARN_STREAM("Warning: Some position entries in parameter " << imuTopicName << "_config are listed true, "
+                          "but sensor_msgs/Imu e contains no information about position");
```
Comment (ayrton04) [inline src/ros_filter.cpp]: Extraneous 'e' here.

**Review by ayrton04 — APPROVED** [review]
Thanks for this! Please fix the warning I mentioned, but the rest LGTM.

File: src/ros_filter.cpp (hunk 1 above)
Comment (johuber) [reply src/ros_filter.cpp]: fixed

**Review by ayrton04 — APPROVED** [review]

**Comment by ayrton04** [comment]
Thanks again. Will merge once the build farm gets done.
