### PR TITLE
Fix warning "Failed to meet update rate!"

### LINKED ISSUE #601: Failed to meet update rate!
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source from git repo
- Version or commit hash:
  - HEAD of melodic-devel branch

#### Description

We are running the ekf_localization_node on a Clearpath Jackal.

Commit edc5bea3 causes the performance of the filter to be very poor, and the node continuously logs the warning "Failed to meet update rate!" This message happens many times per second.

This commit causes an access to the ros parameter server for every IMU packet that arrives. On the Jackal, this message comes into the filter at 75 Hz, so the node is trying to access the parameter server every 13 milliseconds. In our environment, the ROS master and parameter server do not run locally on the robot. The robot communciates over a wireless link to a server, and this param() call sometimes takes > 50 milliseconds to execute. That causes input queue overflow and very erratic timing of the filter update callback.

One way to fix this is to cache the silent_tf_failure flag in the RosFilter class. I will submit a pull request shortly.

#### Steps to reproduce issue

See descrption.

#### Expected behavior

See description.

#### Actual behavior

See description.

### PR DESCRIPTION
**Pull request by mjs973**
This patch reads the parameter server key silent_tf_failure only once at startup. It resolves #601.

### CODE REVIEW

File: include/robot_localization/ros_filter.h [hunk 1]
```diff
@@ -476,6 +476,10 @@ template<class T> class RosFilter
     //!
     bool useControl_;
 
+    //! @brief Whether or not to print warning for tf lookup failure
+    //!
+    bool silent_tf_failure_;
```
Comment (ayrton04) [inline include/robot_localization/ros_filter.h]: Thank you very much for both catching and addressing this issue.

Given that this is against `melodic-devel`, and we're still using the old (and technically incorrect) style for variable names in this branch, would you mind making this consistent with the others, and changing this to `silentTfFailure_`? I'll make sure it matches the style when I cherry pick it into the other branches. Thanks!

**Review by ayrton04 — APPROVED** [review]

File: include/robot_localization/ros_filter.h (hunk 1 above)
Comment (mjs973) [reply include/robot_localization/ros_filter.h]: My branch has been updated with this change.

**Review by ayrton04 — APPROVED** [review]

**Comment by ayrton04** [comment]
Thanks again!
